Fix for issue 221
git-svn-id: https://oscars.es.net/repos/oscars/trunk@9656 c75a6b91-02ef-0310-b74a-e20389c9c41d

diff --git a/tools/bin/confDragonPSS b/tools/bin/confDragonPSS
--- a/tools/bin/confDragonPSS
+++ b/tools/bin/confDragonPSS
@@ -23,9 +23,14 @@ getConfigFile () {
                 echo "Error: Argument list insufficient"
                 exit 1;
         fi
-#       echo "$1, $2, $3"
+        #echo "$1, $2, $3 $4"
+	fileArg=$4
+        if [ -z $fileArg ]; then
+                #echo "Filename empty"
+                fileArg=""
+        fi
 #TDB run from OSCARS_HOME?
-        Config=$(sh $OSCARS_DIST/bin/parseManifest.sh $1 $2 $3 $4| sed "s/'//g")
+        Config=$(sh $OSCARS_DIST/bin/parseManifest.sh $1 $2 $3 $fileArg| sed "s/'//g")
 #       echo "Config in local Method :$Config"
         Service=$(echo $Config | awk -F/ '$1~//{print $2}')
         Conf=$(echo $Config | awk -F/ '$1~//{print $3}')
@@ -143,7 +148,14 @@ LOCAL_DOMAIN_ID="localDomainId"
 #CIRCUIT_SERVICE=
 
 #Get all variable values from the file
-Config2=$(getConfigFile PSSService $CONTEXT dragonPSS)
+#Config2=$(getConfigFile PSSService $CONTEXT dragonPSS)
+Config2=$(getConfigFile PSSService PSSService $CONTEXT)
+#if file not found, return
+if [ -z $Config2 ] || [ ! -f $Config2 ]; then
+        echo "The configuration file is not found. Check if your $OSCARS_HOME/PSSService/conf folder has configuration files present"
+        exit 1
+fi
+
 #echo "config file= $Config2"
 
 #get current Local Domain used
@@ -175,8 +187,14 @@ sed -i -e "s/$stubLine/$final_str/" $Config2
 #New file. could move this to another script, but keeping it here for now
 #get other config file
 #config-connector-directory.yaml
-connector_config=$(getConfigFile PSSService $CONTEXT dragonPSS config-connector-directory.yaml)
+#connector_config=$(getConfigFile PSSService $CONTEXT dragonPSS config-connector-directory.yaml)
+connector_config=$(getConfigFile PSSService PSSService $CONTEXT config-connector-directory.yaml)
 #echo "Connector == $connector_config"
+#if file not found, return
+if [ -z $connector_config ] || [ ! -f $connector_config ]; then
+        echo "The configuration file is not found. Check if your $OSCARS_HOME/PSSService/conf folder has configuration files present"
+        exit 1
+fi
 
 #kludge. code is slow, will need to be bettered
 params=( cliUser cliPassword promptPattern sshPortForward sshUser sshKey sshPort localAddress remotePort hasNarb setERO tunnelMode )
diff --git a/tools/bin/idc-configPSS b/tools/bin/idc-configPSS
--- a/tools/bin/idc-configPSS
+++ b/tools/bin/idc-configPSS
@@ -106,9 +106,14 @@ PSSChoice="PSSChoice"
 
 
 #Search topology file and get the values
-Config2=$(getConfigFile Utils $CONTEXT utils) #configFile
-
-echo "The config file location is $Config2"
+#Config2=$(getConfigFile Utils $CONTEXT utils) #configFile
+Config2=$(getConfigFile Utils Utils $CONTEXT) #configFile
+#if file not found, return
+if [ -z $Config2 ] || [ ! -f $Config2 ]; then
+        echo "The configuration file is not found. Check if your $OSCARS_HOME/Utils/conf folder has configuration files present"
+        exit 1
+fi
+#echo "The config file location is $Config2"
 
 #prompt user for new domain
 printf "Enter the PSS (Path setup subsystem) you would like to use: Stub/Dragon/EoMPLS? ";
@@ -128,9 +133,8 @@ PSSLine="PSSChoice:\t$user_choice"
 #TBD write if not found/replace
 #echo -e "$PSSLine" >> $Config2
 ifPSSChoicePresent=$(awk -F: '$1~/PSSChoice/{print "FOUND"}' $Config2)
-echo "PSS found: :$ifPSSChoicePresent:, config=$Config2, PSSLine=$PSSLine, Choice=:$PSSChoice:"
+#echo "PSS found: :$ifPSSChoicePresent:, config=$Config2, PSSLine=$PSSLine, Choice=:$PSSChoice:"
 if [ "$ifPSSChoicePresent" == "FOUND" ]; then
-	echo "i------------FOUND"
 	sed -i -e "s/"$PSSChoice":.*/"$PSSLine"/" $Config2
 	#sed -i -e "s/.*/"$PSSLine"/" $Config2
 else
diff --git a/tools/bin/idc-domaininfoadd b/tools/bin/idc-domaininfoadd
--- a/tools/bin/idc-domaininfoadd
+++ b/tools/bin/idc-domaininfoadd
@@ -81,9 +81,25 @@ SOURCE="source"
 printf "Enter the new domain you would like to add:";
 read user_domain;
 stty echo;
+#trim string
+user_domain=$(echo $user_domain | sed 's/^ *\(.*\) *$/\1/')
 
 #Search topology file and get the config file name
-config_file=$(getConfigFile TopoBridgeService $CONTEXT topoBridge)
+#config_file=$(getConfigFile TopoBridgeService $CONTEXT topoBridge)
+config_file=$(getConfigFile TopoBridgeService TopoBridgeService $CONTEXT)
+#if file not found, return
+if [ -z $config_file ] || [ ! -f $config_file ]; then
+        echo "The configuration file is not found. Check if your $OSCARS_HOME/TopoBridgeService/conf folder has configuration files present"
+        exit 1
+fi
+
+#do not re-add the same domain
+localDmId=$(awk -F: '$1~/'\'$user_domain\''/{print "FOUND"}' $config_file) 
+echo "localdm = $localDmId, user=$user_domain"
+if [[ "$localDmId" == *FOUND* ]]; then
+	echo "--This domain is already present. Use idc-domaininfomod to modify further"
+	exit 1
+fi
 
 printf "Enter the source of the topology for this domain: file/topoServer?";
 #stty echo;
@@ -119,7 +135,7 @@ fi
 	
 #Redirect domain addition to file
 # did not see it necessary to parse the file to check for "domains", and then append
-domain_str="\n\t'$user_domain':\n\t    $SOURCE:\t'$user_src'\n\t    $USER_SRC_TYPE:\t$user_location"
+domain_str="\n        '$user_domain':\n            $SOURCE:         '$user_src'\n            $USER_SRC_TYPE:           $user_location"
 echo -e "$domain_str" >> $config_file
 if [ $? == 0 ]; then
 	echo "--Domain $user_domain added succesfully"
diff --git a/tools/bin/idc-domaininfomod b/tools/bin/idc-domaininfomod
--- a/tools/bin/idc-domaininfomod
+++ b/tools/bin/idc-domaininfomod
@@ -76,6 +76,8 @@ if [ "$CONTEXT" ==  "PRODUCTION" ] || [ "$CONTEXT" == "UNITTEST" ] || [ "$CONTEX
 	printf "Enter the domain you would like to modify for context $CONTEXT:";
 	read user_domain;
 	stty echo;
+	#trim string
+        user_domain=$(echo $user_domain | sed 's/^ *\(.*\) *$/\1/')
 	echo "--Trying to locate domain $user_domain..."
 else
 	echo "CONTEXT  $CONTEXT is not recognized"
@@ -85,7 +87,13 @@ fi
 SOURCE="source"
 
 #Search topology file and get the config file name
-config_file=$(getConfigFile TopoBridgeService $CONTEXT topoBridge)
+#config_file=$(getConfigFile TopoBridgeService $CONTEXT topoBridge)
+config_file=$(getConfigFile TopoBridgeService TopoBridgeService $CONTEXT)
+#if file not found, return
+if [ -z $config_file ] || [ ! -f $config_file ]; then
+        echo "The configuration file is not found. Check if your $OSCARS_HOME/TopoBridgeService/conf folder has configuration files present"
+        exit 1
+fi
 
 SOURCE="source"
 DMNFND=0
@@ -147,6 +155,9 @@ elif [ $DMNFND -eq 1 ]; then
 		read user_src;
 		if [ "$user_src" != "file" ] && [ "$user_src" != "topoServer" ]; then
 			user_src=0;
+			#error message to user 
+			echo "--You did not select a valid value for file/toposerver. Quitting now"
+			exit 1;
 		fi
 	done
 	#if file prompt for file location
@@ -172,17 +183,17 @@ elif [ $DMNFND -eq 1 ]; then
 fi
 
 # did not see it necessary to parse the file to check for "domains", and then append
-src_line="\t\t$SOURCE:\t'$user_src'"
-location_line="\t\t$USER_SRC_TYPE:\t$user_location"
+src_line="            $SOURCE:         '$user_src'"
+location_line="            $USER_SRC_TYPE:           $user_location"
 
 sed -i -e ""$srcLine"s/.*/$src_line/" $config_file
 sed -i -e ""$filenameLine"s/.*/$location_line/" $config_file
 
 if [ $? == 0 ]; then
-	echo "Domain $user_domain added succesfully"
+	echo "Domain $user_domain modified succesfully"
 	#echo "$File : $config_file"
 else
-	echo "There was an error while adding the new domain to $config_file. Please add a domain to this file manually"
+	echo "There was an error while modifying domain $user_domain in $config_file. Please modify this manually"
 fi
 
 
diff --git a/tools/bin/idc-localdomainmod b/tools/bin/idc-localdomainmod
--- a/tools/bin/idc-localdomainmod
+++ b/tools/bin/idc-localdomainmod
@@ -2,7 +2,7 @@
 #########################################################################
 # Script used to view current local domain
 # Usage: idc-domainmod <context>
-# TDB: Removing echo/prints. Retaining expecting future changes
+# TBD: Removing echo/prints. Retaining expecting future changes
 # TBD: Run from OSCARS_HOME. Right now run from OSCARS_DIST
 #########################################################################
 
@@ -23,9 +23,16 @@ getConfigFile () {
 		echo "Error: Argument list insufficient"
 		exit 1;
 	fi
-#	echo "$1, $2, $3"
-#TDB run from OSCARS_HOME?
+#TBD run from OSCARS_HOME?
 	Config=$(sh $OSCARS_DIST/bin/parseManifest.sh $1 $2 $3 | sed "s/'//g")
+	#Should find manifest file, and it should have the config line we're looking for.
+	##If not, there is some error in either the manifest file copy, or the manifest file that is copied
+	if [ -z $Config ]; then
+                echo "The manifest file is not found/is invalid. Have you run the bin/copyTemplates.sh and/or bin/exportconfig commands?"
+
+                exit 1
+        fi
+
 #	echo "Config in local Method :$Config"
 	Service=$(echo $Config | awk -F/ '$1~//{print $2}')
 	Conf=$(echo $Config | awk -F/ '$1~//{print $3}')
@@ -50,7 +57,6 @@ else
 	exit 1
 fi
 
-#TBD remove later
 if  [ -z $OSCARS_DIST ]; then
     echo "Please set the environment var OSCARS_DIST to the OSCARS source directory"
     exit -1
@@ -70,9 +76,15 @@ case $1 in
 esac
 
 #Search topology file and get the values
-Config2=$(getConfigFile Utils $CONTEXT utils) #configFile
+#Config2=$(getConfigFile Utils $CONTEXT utils) #configFile
+Config2=$(getConfigFile Utils Utils $CONTEXT) 
+#if file not found, return
+if [ -z $Config2 ] || [ ! -f $Config2 ]; then
+	echo "The configuration file is not found. Check if your $OSCARS_HOME/Utils/conf folder has configuration files present"
+	exit 1
+fi
 
-#echo "The config file location is $Config2"
+
 
 SVCFND=0
 CONTFND=0
@@ -83,21 +95,29 @@ printf "Enter the new domain you would like to use as the local domain: ";
 read user_choice;
 stty echo;
 echo "";
+#trim string
+user_choice=$(echo $user_choice | sed 's/^ *\(.*\) *$/\1/')
 
 #Get all topo files to check if this topology is present
 #Edit  $OSCARS_HOME/TopoBridgeService/conf /config.XXX.yaml
-topoConfigFile=$(getConfigFile TopoBridgeService $CONTEXT topoBridge) #configFile
+#topoConfigFile=$(getConfigFile TopoBridgeService $CONTEXT topoBridge) #configFile
+topoConfigFile=$(getConfigFile TopoBridgeService TopoBridgeService $CONTEXT) 
+#If file not found, return
+if [ -z $topoConfigFile ] || [ ! -f $topoConfigFile ]; then
+        echo "The configuration file is not found. Have you run the bin/copyTemplates.sh and/or bin/exportconfig commands? "
+        exit 1
+fi
 
 #Check if user's choice is present in current list of topology files
 #echo "Config File where all domains are found= $topoConfigFile"
-isDomainFound=$(awk -F: '$1~/'$user_choice'/{print "FOUND"}' $topoConfigFile)
+#quotes to avoid duplicate matches like testdomain-1, testdomain-11 when searching for testdomain-1
+isDomainFound=$(awk -F: '$1~/'\'$user_choice\''/{print "FOUND"}' $topoConfigFile)
 if [ "$isDomainFound" != "FOUND" ]; then
 	echo "--NOTE: Your choice of domain is not found in the current set of configured topologies."
 	echo "--Run idc-domainadd to add this new domain"
 fi
 
 #get current Local Domain used
-#TBD manifest location
 lineNum=0;
 while read i; 
 do
@@ -121,7 +141,7 @@ do
 			localDomain=$(echo $Line | awk -F: '$1~/id/{print $2}' | sed "s/'//g")
 			CONTFND=0
 		#fi
-		echo "localDomain=$localDomain. Linenum = $lineNum"
+		#echo "localDomain=$localDomain. Linenum = $lineNum"
 		#trimming
                 localDomain=$(echo $localDomain | sed 's/^ *\(.*\) *$/\1/')
 		break;
@@ -131,7 +151,8 @@ done<$Config2
 		
 #got line number and localDomain. Replace now
 echo "--Replacing your current local domain from $localDomain to $user_choice"; 
-sed -i -e ""$lineNum"s/$localDomain/$user_choice/" $Config2
+#sed -i ""$lineNum"s/$localDomain/$user_choice/" $Config2
+sed -i ""$lineNum"s/id:.*\'$localDomain\'/id: \'$user_choice\'/" $Config2
 if [ $? != 0 ]; then
 	echo "-- Sed returned an error when updating $Config2. Please manually change the localDomain identifier in this file";
 else
diff --git a/tools/bin/idc-localdomainview b/tools/bin/idc-localdomainview
--- a/tools/bin/idc-localdomainview
+++ b/tools/bin/idc-localdomainview
@@ -19,7 +19,12 @@ fi
 
 ## define context to be production, since the local Domain is defined in just one place
 CONTEXT=PRODUCTION
-Config=$(sh $OSCARS_DIST/bin/parseManifest.sh Utils $CONTEXT utils) # | sed "s/'//g")
+#Config=$(sh $OSCARS_DIST/bin/parseManifest.sh Utils $CONTEXT utils) # | sed "s/'//g")
+Config=$(sh $OSCARS_DIST/bin/parseManifest.sh Utils Utils $CONTEXT | sed "s/'//g")
+if [ -z $Config ]; then
+      echo "The manifest file is not found/or is invalid. Have you run the bin/copyTemplates.sh and/or bin/exportconfig commands?"
+      exit 1
+fi
 Service=$(echo $Config | awk -F/ '$1~//{print $2}')
 Conf=$(echo $Config | awk -F/ '$1~//{print $3}')
 Yaml=$(echo $Config | awk -F/ '$1~//{print $4}' | sed "s/'//g")
@@ -29,6 +34,13 @@ elif [ "$Conf" == "config" ]; then
 	configFile=$OSCARS_DIST/$Service/$Conf/$Yaml
 fi
 #echo "The config file location is $configFile"
+
+if [ -z $configFile ] || [ ! -f $configFile ]; then
+	echo "The configuration file is not found. You may have to:"
+	echo "  1. Rerun this script after running copyTemplates.sh and/or bin/exportconfig"
+	echo "  2. alternatively, look up the local domain used in $OSCARS_HOME/Utils/conf/config.yaml (if present)"
+	exit 1
+fi
 
 SVCFND=0
 CONTFND=0
diff --git a/tools/bin/idc-portmod b/tools/bin/idc-portmod
--- a/tools/bin/idc-portmod
+++ b/tools/bin/idc-portmod
@@ -15,7 +15,6 @@ else
         exit 1
 fi
 
-#TBD Remove later
 if  [ -z $OSCARS_DIST ]; then
 	echo "Please set the environment var OSCARS_DIST to the OSCARS source directory"
 	exit -1
@@ -35,6 +34,43 @@ printUsage() {
 	exit 1
 }
 
+#######################################################################
+#subroutine to get configFile
+# introduced this and removed local fetches of config File
+#######################################################################
+getConfigFile () {
+        if [ $# -lt 3 ]; then
+                echo "Error: Argument list insufficient"
+                exit 1;
+        fi
+	fileArg=$4
+        if [ -z $fileArg ]; then
+		#echo "Filename empty"
+		fileArg=""
+	fi
+        Config=$(sh $OSCARS_DIST/bin/parseManifest.sh $1 $2 $3 $fileArg | sed "s/'//g")
+        #Should find manifest file, and it should have the config line we're looking for.
+        ##If not, there is some error in either the manifest file copy, or the manifest file that is copied
+        if [ -z $Config ]; then
+                #echo "The manifest file is not found/is invalid. Have you run the bin/copyTemplates.sh and/or bin/exportconfig commands?"
+                exit 1
+        fi
+
+	#       echo "Config in local Method :$Config"
+        Service=$(echo $Config | awk -F/ '$1~//{print $2}')
+        Conf=$(echo $Config | awk -F/ '$1~//{print $3}')
+        Yaml=$(echo $Config | awk -F/ '$1~//{print $4}' | sed "s/'//g")
+	#       echo "2. $Service, $Conf, $Yaml"
+        if [ "$Conf" == "conf" ]; then
+                configFile=$OSCARS_HOME/$Service/$Conf/$Yaml
+        elif [ "$Conf" == "config" ]; then
+                configFile=$OSCARS_DIST/$Service/$Conf/$Yaml
+        fi
+        # 	echo "3. Config File: $configFile"
+	echo $configFile
+}
+
+
 ###########################################################################
 #Subroutines to find port
 ###########################################################################
@@ -50,25 +86,26 @@ findPort() {
 		echo "--You chose to retain the same port number"
 		return 0;
 	fi
-	Config=$(sh $OSCARS_DIST/bin/parseManifest.sh $SERVICE $CONTEXT $fileLoc | sed "s/'//g")
-	#echo "Config file:$Config"
-	Service=$(echo $Config | awk -F/ '$1~//{print $2}')
-#echo "Service :$Service"	
-	Conf=$(echo $Config | awk -F/ '$1~//{print $3}')
-	Yaml=$(echo $Config | awk -F/ '$1~//{print $4}' | sed "s/'//g")
-	#echo "Conf: $Conf, Yaml=$Yaml";
+	#Config=$(sh $OSCARS_DIST/bin/parseManifest.sh $SERVICE $CONTEXT $fileLoc | sed "s/'//g")
+	ConfigFile=$(getConfigFile $fileLoc $SERVICE $CONTEXT $file)
+	if [ -z $ConfigFile ] || [ ! -f $ConfigFile ] ; then
+        	echo "The manifest file is not found/is invalid. "
+		echo "Have you run the bin/copyTemplates .sh and/or bin/exportconfig commands?"
+                exit 1
+        fi
+
 	#get server configuration from server-cxf...yaml now
-	serverConfig=$(sh $OSCARS_DIST/bin/parseManifest.sh $SERVICE $CONTEXT $fileLoc server-cxf.xml| sed "s/'//g")
-	#echo "Server config file: $serverConfig"
-	Service_cxf=$(echo $serverConfig | awk -F/ '$1~//{print $2}')
-	Conf_cxf=$(echo $serverConfig| awk -F/ '$1~//{print $3}')
-	Yaml_cxf=$(echo $serverConfig | awk -F/ '$1~//{print $4}' | sed "s/'//g")
-	#echo "Conf: $Conf_cxf, Yaml=$Yaml_cxf";	
-	if [ "$Conf" == "conf" ]; then
-		port=$(awk -F: '$1~/publishTo/{print $4}' $OSCARS_HOME/$Service/$Conf/$Yaml)
-	elif [ "$Conf" == "config" ]; then
-		port=$(awk -F: '$1~/publishTo/{print $4}' $OSCARS_DIST/$Service/$Conf/$Yaml)
-	fi
+	#serverConfig=$(sh $OSCARS_DIST/bin/parseManifest.sh $SERVICE $CONTEXT $fileLoc server-cxf.xml| sed "s/'//g")
+	serverConfig=$(getConfigFile $fileLoc $SERVICE $CONTEXT server-cxf.xml)
+	if [ -z $serverConfig ] || [ ! -f $serverConfig ]; then
+                echo "The configuration file is not found. You either have to :"
+                echo "  1. Rerun this script after running copyTemplates.sh and/or bin/exportconfig, or "
+                echo "  2. Change files \"$OSCARS_HOME/<service>/conf/server-cxf-ssl.xml or server-cxf-http.xml\" "
+		echo " and \" $OSCARS_HOME/<service>/conf/<service>.SSL.xml or HTTP.yaml\" files manually to change port numbers "
+		exit 1
+        fi
+	
+	port=$(awk -F: '$1~/publishTo/{print $4}' $ConfigFile)
 	port=$(echo $port | sed "s/[^0-9]//g") 
 	printf "Are you sure you want to replace port number from $port to $userport? y/n ";
 	ans=0;
@@ -79,21 +116,16 @@ findPort() {
    		fi
 	done	
 	if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-		########## The below set of code may be a better way to replace the port, so that no other matching numeric (say, password)
-		############# which may happen to be the same as port number, gets replaced.
-		################ However, need to revisit the "SED" command. Commenting for now
-		#toReplace=$(awk -F: '$1~/publishTo/{print $0}' $OSCARS_HOME/$Service/$Conf/$Yaml)
-		#echo "ToReplace == $toReplace"
-		#replaced=$(echo $toReplace | sed "s/[0-9][0-9]*/$userport/g")
-		#echo "replaced: $replaced END";
-		#sed -i -e "s/$toReplace/$replaced/" $OSCARS_HOME/$Service/$Conf/$Yaml;
-		#################end comment for searching "publishTo...port...etc #################		
 		#sed -i -e "s/[0-9][0-9]*/$userport/g" $OSCARS_HOME/$Service/$Conf/$Yaml;# this would work too
-	
 	  	#######replace the original port with the new one	
-		sed -i -e "s/$port/$userport/g" $OSCARS_HOME/$Service/$Conf/$Yaml;
-		#replace in server_cxf.xml
-		sed -i -e 's/<httpj:engine port=\"'$port'\">/<httpj:engine port=\"'$userport'\">/' $OSCARS_HOME/$Service_cxf/$Conf_cxf/$Yaml_cxf
+ 		#Implemented earlier suggestion to selectively replace the port number in
+		## the "publishTo" line alone, instead of any numeric that may match the port number		
+		#sed -i -e "s/$port/$userport/g" $OSCARS_HOME/$Service/$Conf/$Yaml;
+		sed -i -e 's_\(http.*:\/\/.*\):\([0-9]*\)_\1:'$userport'_' $ConfigFile
+
+		#replace in server_cxf.xml. Replace whatever value you may find for port currently
+		sed -i -e 's/<httpj:engine port=.*>/<httpj:engine port=\"'$userport'\">/' $serverConfig
+		sed -i -e "s/$port/$userport/g" $serverConfig; #a single file refers to port in another line
 		echo "--The port number for $SERVICE has been replaced to $userport";
    		echo "--$SERVICE set to run in context $CONTEXT on port $userport."
 		echo "--Restart service to start using this port."
@@ -108,17 +140,16 @@ viewUIPort(){
    	stty echo;
    	#echo "";
 
-	#Config=$(sh $OSCARS_DIST/bin/parseManifest.sh $SERVICE $CONTEXT $fileLoc )
 	#Config=$(sh $OSCARS_DIST/bin/parseManifest.sh WBUIService $CONTEXT wbui jetty.xml)
-	Config=$(sh $OSCARS_DIST/bin/parseManifest.sh $SERVICE $CONTEXT $fileLoc $file)
-	Service=$(echo $Config | awk -F/ '$1~//{print $2}')
-	Conf=$(echo $Config | awk -F/ '$1~//{print $3}')
-	Yaml=$(echo $Config | awk -F/ '$1~//{print $4}' | sed "s/'//g")
-	if [ "$Conf" == "conf" ]; then
-		port=$(awk -F\" '$4~/jetty.port/{print $6}' $OSCARS_HOME/$Service/$Conf/$Yaml)
-	elif [ "$Conf" == "config" ]; then
-		port=$(awk -F\" '$4~/jetty.port/{print $6}' $OSCARS_DIST/$Service/$Conf/$Yaml)
-	fi
+	#Config=$(sh $OSCARS_DIST/bin/parseManifest.sh $SERVICE $CONTEXT $fileLoc $file)
+	Config=$(getConfigFile $fileLoc $SERVICE $CONTEXT $file)
+	if [ -z $Config ] || [ ! -f $Config ] ; then
+                echo "The manifest file is not found/is invalid. "
+                echo "Have you run the bin/copyTemplates .sh and/or bin/exportconfig commands?"
+                exit 1
+        fi
+
+	port=$(awk -F\" '$4~/jetty.port/{print $6}' $Config)
 	port=$(echo $port | sed "s/[^0-9]//g")
 	printf "Are you sure you want to replace port number from $port to $jettyport? y/n ";
  	ans=0;
@@ -129,17 +160,19 @@ viewUIPort(){
 		fi
 	done
  	if [ "$ans" == "y" ] || [ "$ans" == "Y" ]; then
-	#Again, like in the above subroutine, search for "<SystemProperty name="jetty.port" default="xxxx" before replacing
- 		sed -i -e "s/$port/$jettyport/" $OSCARS_HOME/$Service/$Conf/$Yaml;
-		echo "The port number for $Service has been replaced to $jettyport";
+		#Implemented search for "<SystemProperty name="jetty.port" default="xxxx" before replacing
+ 		#sed -i -e "s/$port/$jettyport/" $Config;
+		sed -i -e 's_SystemProperty name=\"jetty.port\" default=\"'$port'\"_SystemProperty name=\"jetty.port\" default=\"'$jettyport'\"_' $Config
+		echo "--The port number for $SERVICE has been replaced to $jettyport";
 		if [ $? != 0 ]; then
 			echo "--The port number change was not successful."
 			echo "--Please change it manually by changing the entry in lines like "<SystemProperty name="jetty.port" default="xxxx"/>" in file $OSCARS_HOME/$Service/$Conf/$Yaml"
 			exit 1;
         	fi
-		echo "$SERVICE set to run in context $CONTEXT on port $jettyport."
-		echo "Restart this service to start using this port."
+		echo "--$SERVICE set to run in context $CONTEXT on port $jettyport."
+		echo "--Restart this service to start using this port."
 	fi
+
 	
 	#neutralize
 	port=0 
@@ -170,17 +203,20 @@ shift
 
 #loop for "ALL" option
 #Removed WBUI for specific handling
-#_allLocations=(authN authZ api coordinator topoBridge resourceManager stubPSS lookup pce bandwidthPCE connectivityPCE dijkstraPCE vlanPCE pce notificationBridge wsnbroker) #TBD:nullAGG==pce check
+#_allServiceDirs=(authN authZ api coordinator topoBridge resourceManager stubPSS lookup pce bandwidthPCE connectivityPCE dijkstraPCE vlanPCE pce notificationBridge wsnbroker) #TBD:nullAGG==pce check
 #_allServices=(AuthNService AuthZService OSCARSService CoordService TopoBridgeService ResourceManagerService PSSService LookupService StubPCE BandwidthPCE ConnectivityPCE DijkstraPCE VlanPCE NullAggregator NotificationBridgeService WSNBrokerService)
-_allLocations=(authN authZ api coordinator topoBridge resourceManager stubPSS lookup bandwidthPCE connectivityPCE dijkstraPCE vlanPCE pce notificationBridge wsnbroker ) #TBD:nullAGG==pce check
+
+#_allServiceDirs not used anymore. But not deleting it in case of future reuse 
+#_allServiceDirs=(authN authZ api coordinator topoBridge resourceManager stubPSS lookup bandwidthPCE connectivityPCE dijkstraPCE vlanPCE pce notificationBridge wsnbroker ) #TBD:nullAGG==pce check
 _allServices=(AuthNService AuthZService OSCARSService CoordService TopoBridgeService ResourceManagerService PSSService LookupService BandwidthPCE ConnectivityPCE DijkstraPCE VlanPCE NullAggregator NotificationBridgeService WSNBrokerService )
+_allServiceDirs=(AuthNService AuthZService OSCARSService CoordService TopoBridgeService ResourceManagerService PSSService LookupService BandwidthPCE ConnectivityPCE DijkstraPCE VlanPCE PCEService NotificationBridgeService WSNBrokerService)
 
 while [ ! -z $1 ]
     do 
     case $1 in
     ALL)
 	index=0;
-	for fileN in ${_allLocations[@]}
+	for fileN in ${_allServiceDirs[@]}
         do
 		SERVICE=${_allServices[$index]};
 		index=`expr $index + 1`;
@@ -189,29 +225,33 @@ while [ ! -z $1 ]
 	done
 	# now separately call WBUI processing
 	#viewWebUIPort;
-	SERVICE=WBUIService; fileLoc=wbui; file=jetty.xml;viewUIPort;
-	SERVICE=IONUIService; fileLoc=ionui; file=jetty.xml;viewUIPort;
+	#SERVICE=WBUIService; fileLoc=wbui; file=jetty.xml;viewUIPort;
+	#SERVICE=IONUIService; fileLoc=ionui; file=jetty.xml;viewUIPort;
+	SERVICE=WBUIService; fileLoc=WBUIService; file=jetty.xml;viewUIPort;
+	SERVICE=IONUIService; fileLoc=IONUIService; file=jetty.xml;viewUIPort;
 	#file location for each varies
 	;;
-    	authN)    SERVICE=${_allServices[0]}; fileLoc=${_allLocations[0]};findPort ;;#startauthN;;
-    	authZ)    SERVICE=${_allServices[1]}; fileLoc=${_allLocations[0]};findPort;;
-    	api)      SERVICE=${_allServices[2]}; fileLoc=${_allLocations[0]};findPort;;
-    	coord)    SERVICE=${_allServices[3]}; fileLoc=${_allLocations[0]};findPort;;
-    	topoBridge) SERVICE=${_allServices[4]}; fileLoc=${_allLocations[0]};findPort;;
-    	rm)       SERVICE=${_allServices[5]}; fileLoc=${_allLocations[5]};findPort;;
-    	stubPSS)  SERVICE=${_allServices[6]}; fileLoc=${_allLocations[6]};findPort;;
-    	lookup)   SERVICE=${_allServices[7]}; fileLoc=${_allLocations[7]};findPort;;
-    	#wbui)     SERVICE=${_allServices[8]}; fileLoc="${_allLocations[8]} jetty.xml";viewWebUIPort;;
-    	wbui)     SERVICE=WBUIService; fileLoc=wbui; file=jetty.xml;viewUIPort;;
-    	#stubPCE)  SERVICE=${_allServices[8]}; fileLoc=${_allLocations[8]};findPort;;
-    	bwPCE)    SERVICE=${_allServices[8]}; fileLoc=${_allLocations[8]};findPort;;
-    	connPCE)  SERVICE=${_allServices[9]}; fileLoc=${_allLocations[9]};findPort;;
-    	dijPCE)   SERVICE=${_allServices[10]}; fileLoc=${_allLocations[10]};findPort;;
-    	vlanPCE)  SERVICE=${_allServices[11]}; fileLoc=${_allLocations[11]};findPort;;
-    	nullAGG)  SERVICE=${_allServices[12]}; fileLoc=${_allLocations[12]};findPort;;
-    	notifyBridge)     SERVICE=${_allServices[13]}; fileLoc=${_allLocations[13]};findPort;;
-    	wsnbroker) SERVICE=${_allServices[14]}; fileLoc=${_allLocations[14]};findPort;;
-	ionui)  SERVICE=IONUIService; fileLoc=ionui; file=jetty.xml;viewUIPort;;
+    	authN)    SERVICE=${_allServices[0]}; fileLoc=${_allServiceDirs[0]};findPort ;;#startauthN;;
+    	authZ)    SERVICE=${_allServices[1]}; fileLoc=${_allServiceDirs[1]};findPort;;
+    	api)      SERVICE=${_allServices[2]}; fileLoc=${_allServiceDirs[2]};findPort;;
+    	coord)    SERVICE=${_allServices[3]}; fileLoc=${_allServiceDirs[3]};findPort;;
+    	topoBridge) SERVICE=${_allServices[4]}; fileLoc=${_allServiceDirs[4]};findPort;;
+    	rm)       SERVICE=${_allServices[5]}; fileLoc=${_allServiceDirs[5]};findPort;;
+    	stubPSS)  SERVICE=${_allServices[6]}; fileLoc=${_allServiceDirs[6]};findPort;;
+    	eomplsPSS)  SERVICE=${_allServices[6]}; fileLoc=${_allServiceDirs[6]};findPort;;
+    	dragonPSS)  SERVICE=${_allServices[6]}; fileLoc=${_allServiceDirs[6]};findPort;;
+    	lookup)   SERVICE=${_allServices[7]}; fileLoc=${_allServiceDirs[7]};findPort;;
+    	#wbui)     SERVICE=${_allServices[8]}; fileLoc="${_allServiceDirs[8]} jetty.xml";viewWebUIPort;;
+    	wbui)     SERVICE=WBUIService; fileLoc=WBUIService; file=jetty.xml;viewUIPort;;
+    	#stubPCE)  SERVICE=${_allServices[8]}; fileLoc=${_allServiceDirs[8]};findPort;;
+    	bwPCE)    SERVICE=${_allServices[8]}; fileLoc=${_allServiceDirs[8]};findPort;;
+    	connPCE)  SERVICE=${_allServices[9]}; fileLoc=${_allServiceDirs[9]};findPort;;
+    	dijPCE)   SERVICE=${_allServices[10]}; fileLoc=${_allServiceDirs[10]};findPort;;
+    	vlanPCE)  SERVICE=${_allServices[11]}; fileLoc=${_allServiceDirs[11]};findPort;;
+    	nullAGG)  SERVICE=${_allServices[12]}; fileLoc=${_allServiceDirs[12]};findPort;;
+    	notifyBridge)     SERVICE=${_allServices[13]}; fileLoc=${_allServiceDirs[13]};findPort;;
+    	wsnbroker) SERVICE=${_allServices[14]}; fileLoc=${_allServiceDirs[14]};findPort;;
+	ionui)  SERVICE=IONUIService; fileLoc=IONUIService; file=jetty.xml;viewUIPort;;
     	*)        echo $1 not a recognized server
   esac
   shift
diff --git a/tools/bin/idc-toposerveradd b/tools/bin/idc-toposerveradd
--- a/tools/bin/idc-toposerveradd
+++ b/tools/bin/idc-toposerveradd
@@ -1,4 +1,4 @@
-#!/bin/sh
+
 ############################################################################
 # Script used to add a new topoServer. This script is used to only add a
 # TS to a currently used domain. To add a new domain and an associated TS ,
@@ -77,6 +77,7 @@ if [ "$CONTEXT" ==  "PRODUCTION" ] || [ "$CONTEXT" == "UNITTEST" ] || [ "$CONTEX
 	printf "Enter the domain for which you would like to add a topoServer. Options: */specific domain name : ";
 	read user_domain;
 	stty echo;
+	user_domain=$(echo $user_domain | sed 's/^ *\(.*\) *$/\1/')
 	echo "--Locating domain $user_domain"
 else
 	echo "CONTEXT $CONTEXT is not recognized"
@@ -84,8 +85,15 @@ else
 fi
 
 #Search topology file and get the config file name
-config_file=$(getConfigFile TopoBridgeService $CONTEXT topoBridge)
+#config_file=$(getConfigFile TopoBridgeService $CONTEXT topoBridge)
+config_file=$(getConfigFile TopoBridgeService TopoBridgeService $CONTEXT)
 #echo "Config file= $config_file"
+#if file not found, return
+if [ -z $config_file ] || [ ! -f $config_file ]; then
+        echo "The configuration file is not found. Check if your $OSCARS_HOME/TopoBridgeService/conf folder has configuration files present"
+        exit 1
+fi
+
 
 #Find if domain is already present, else instruct user to add domain and associated TS.
 SOURCE="source"
@@ -104,7 +112,8 @@ do
         lineNum=`expr $lineNum + 1`
 	#echo "$lineNum:$Line, DNMFND:$DMNFND, ISTOP: $ISTOPOSERVER, SERVER:$SERVERLISTFOUND"
         if [ $DMNFND -eq 0 ]; then
-                localDmId=$(echo $Line | awk -F: '$1~/'$user_domain'/{print "FOUND"}' ) # '{if ( $1~"$user_domain" ) print "FOUND"}')
+		#quotes to avoid duplicate search results
+                localDmId=$(echo $Line | awk -F: '$1~/'\'$user_domain\''/{print "FOUND"}' ) # '{if ( $1~"$user_domain" ) print "FOUND"}')
                 if [ "$localDmId" == "FOUND" ]; then
                         DMNFND=1
 			domainLineNum=$lineNum			
@@ -151,7 +160,7 @@ elif [ $DMNFND == 1 ] && [ $ISTOPOSERVER -eq 0 ]; then
 fi
 
 #Replace in file
-domain_str="\t    $SERVERS:\t$STARTDELIM$serverList'$user_TS'$ENDDELIM"
+domain_str="            $SERVERS:        $STARTDELIM$serverList'$user_TS'$ENDDELIM"
 sed -i -e ""$lineNum"s/.*/$domain_str/" $config_file
 if [ $? == 0 ]; then
 	echo "Topology Server $user_TS has been added succesfully"
