Added option to ask user whether sshPortForwarding config is to be done. Removed 'tunnelMode' config option
git-svn-id: https://oscars.es.net/repos/oscars/trunk@10173 c75a6b91-02ef-0310-b74a-e20389c9c41d

diff --git a/tools/bin/confDragonPSS b/tools/bin/confDragonPSS
--- a/tools/bin/confDragonPSS
+++ b/tools/bin/confDragonPSS
@@ -45,8 +45,103 @@ getConfigFile () {
         echo $configFile
 }
 
+#########################################################################
+# Sub to read file and parse values into array
+#########################################################################
+read_file_parse() {
+	CONTFND=0
+	DRGN_VLSR="dragon-vlsr"
+	lineNum=0;
+	next_id_started=0
+	index=0
+
+	while read i;
+	do
+        	Line=$(echo $i)
+        	#Trim
+        	Line=$(echo $Line | sed 's/^ *\(.*\) *$/\1/')
+       		#increment line num
+        	lineNum=`expr $lineNum + 1`
+        	iscomment=$(echo $Line | awk '/^#/ {print "comment"}')
+       		if [ "$iscomment" == "comment" ]; then
+                	#echo "comment found"
+                	continue;
+        	elif [ "$next_id_started" -eq 1 ]; then
+                	break;
+        	fi
+        	#lineNum=`expr $lineNum + 1`
+        	#echo "-$lineNum: $Line"
+        	if [ $CONTFND -eq 0 ]; then
+                	localDmId=$(echo $Line | awk -F: '$2~/'$DRGN_VLSR'/{print "FOUND"}')
+                	if [ "$localDmId" == "FOUND" ]; then
+                       		CONTFND=1
+                        	#echo "FOUND dragon"
+                	fi
+        	elif [ $CONTFND -eq 1 ] && [ $next_id_started -eq 0 ]; then
+                	for paramSearch in ${params[@]}
+                	do
+                        	CON2=$(echo $Line|awk -F: '$1~/'$paramSearch'/{print '$lineNum',":",$1,":",$2}'| sed "s/'//g") # $2 $lineNum }')
+                        	NextID=$(echo $Line | awk -F: '$1~/id/ {print "IDFOUND"}')
+                        	CON2=$(echo $CON2 | sed 's/^ *\(.*\) *$/\1/')
+                        	if [ ! -z "$CON2" ]; then
+                                	values[$index]="$CON2"
+                                	index=`expr $index + 1`
+			        	break;
+                        	elif [  "$NextID" == "IDFOUND" ] ; then
+                                	next_id_started=1
+                                	CONTFND=0
+                                	break;
+                        	fi
+
+                	done
+       		else
+                	break;
+        	fi
+	done<$connector_config
+}
+
+
+#########################################################################
+# sub to prompt user for values to configuration options 
+#   read in from the config file.
+#########################################################################
+prompt_user_entries() {
+	arraySize=${#values[@]};
+	if [ "$arraySize" -gt 0 ]; then
+        	echo "Press RETURN to retain current value. Or enter new value"
+	fi
+	IFS=';'
+	#echo "Array size:${#values[@]}"
+	for val in ${values[@]}
+        	do
+                	#echo -e "\nVal=$val"
+                	if [ -z "`echo "$val" | tr -d '\n'`" ]; then
+                        	continue
+                	fi
+                	lineNum=$(echo $val | awk -F: '{print $1}')
+                	key=$(echo $val | awk -F: '{print $2}')
+                	value=$(echo $val | awk -F: '{print $3}')
+                	#trim value
+                	value=$(echo $value| awk '{gsub(/^[ \t]+|[ \t]+$/,"")};1') #sed 's/^ *\(.*\) *$/\1/')
+                	printf  "\n $key:[$value]?";
+                	read user_value </dev/tty 2>/dev/tty
+                	#read  -sn1 user_value < $(tty)
+                	#stty echo
+                	#-z "`echo "$VARIABLE" | tr -d '\n'`" `
+                	if [ ! -z "`echo "$user_value" | tr -d '\n'`" ]; then
+                        	printf "Changing $value to $user_value"
+                        	sed -i -e ""$lineNum"s%"$value"%"$user_value"%" $connector_config
+                	fi
+                	#error
+                	if [ $? != 0 ]; then
+                        	echo "-- Sed returned an error when updating value "$key:$value". Please change this line manually in file $eonnector_config";
+                	fi
+		done
+} 
+
+
 #************************************************************************
-#sub to find if files exist
+# sub to find if files exist
 #************************************************************************
 file_exists ()
 {
@@ -121,7 +216,7 @@ if [ $? -eq 0 ]; then
                 echo "This means you are choosing to work with the old set of configuration files." 
                 echo "It may also result in errors if relevant/necessary files are not found."
                 echo "Would you want to continue? Y|N"
-                read nocopy_ans;
+                #read nocopy_ans;
                 while [ $nocopy_ans == 0 ]; do
                         read nocopy_ans;
                         if [ "$nocopy_ans" != "y" ] && [ "$nocopy_ans" != "Y" ] && [ "$nocopy_ans" != "n" ] && [ "$nocopy_ans" != "N" ]; then
@@ -136,8 +231,7 @@ if [ $? -eq 0 ]; then
                 fi
         fi
 else
-      #run exportconfig to copy DragonPSS files into $OSCARS_HOME/PSSService
-	#TBD Check path
+	#run exportconfig to copy DragonPSS files into $OSCARS_HOME/PSSService
 	(sh $OSCARS_DIST/dragonPSS/bin/exportconfig $OSCARS_DIST $OSCARS_HOME)
 fi
 echo "Getting configuration variables ...."
@@ -196,91 +290,30 @@ if [ -z $connector_config ] || [ ! -f $connector_config ]; then
         exit 1
 fi
 
-#kludge. code is slow, will need to be bettered
-params=( cliUser cliPassword promptPattern sshPortForward sshUser sshKey sshPort localAddress remotePort hasNarb setERO tunnelMode )
-values=( 'dragon' 'dragon' 'vlsr' true 'dragon' '/home/dragon/.ssh/id_rsa' 22 '127.0.0.1' 2611 true true false )
+# get values for common input parameters
+params=( cliUser cliPassword promptPattern hasNarb setERO )
+values=( 'dragon' 'dragon' 'vlsr' true true )
+read_file_parse
+prompt_user_entries
 
-CONTFND=0
-DRGN_VLSR="dragon-vlsr"
-lineNum=0;
-next_id_started=0
-index=0
-
-while read i;
-do
-        Line=$(echo $i)
-	#Trim
-	Line=$(echo $Line | sed 's/^ *\(.*\) *$/\1/')
-        #increment line num
-        lineNum=`expr $lineNum + 1`
-        iscomment=$(echo $Line | awk '/^#/ {print "comment"}')
-        if [ "$iscomment" == "comment" ]; then
-                #echo "comment found"
-                continue;
-        elif [ "$next_id_started" -eq 1 ]; then
-                break;
+# get values for sshPortForward config, if needed by user 
+sshFwd_ans=0;
+printf "\nWould you want to configure sshPortForwarding parameters? Y|N"
+while [ $sshFwd_ans == 0 ]; do
+	read sshFwd_ans;
+	if [ "$sshFwd_ans" != "y" ] && [ "$sshFwd_ans" != "Y" ] && [ "$sshFwd_ans" != "n" ] && [ "$sshFwd_ans" != "N" ]; then
+       		sshFwd_ans=0;
         fi
-        #lineNum=`expr $lineNum + 1`
-        #echo "----$lineNum: $Line"
-        if [ $CONTFND -eq 0 ]; then
-                localDmId=$(echo $Line | awk -F: '$2~/'$DRGN_VLSR'/{print "FOUND"}')
-                if [ "$localDmId" == "FOUND" ]; then
-                        CONTFND=1
-                        #echo "FOUND dragon"
-                fi
-        elif [ $CONTFND -eq 1 ] && [ $next_id_started -eq 0 ]; then
-                for paramSearch in ${params[@]}
-                do
-                        CON2=$(echo $Line|awk -F: '$1~/'$paramSearch'/{print '$lineNum',":",$1,":",$2}'| sed "s/'//g") # $2 $lineNum }')
-                        NextID=$(echo $Line | awk -F: '$1~/id/ {print "IDFOUND"}')
-                        CON2=$(echo $CON2 | sed 's/^ *\(.*\) *$/\1/')
-                        if [ ! -z "$CON2" ]; then
-                                #echo "found: $CON2"
-                                values[$index]="$CON2"
-                                index=`expr $index + 1`
-      break;
-                        elif [  "$NextID" == "IDFOUND" ] ; then
-                                #echo "Quiting now"
-                                next_id_started=1
-                                CONTFND=0
-                                break;
-                        fi
-
-                done
-        else
-                break;
-        fi
-done<$connector_config
-
-arraySize=${#values[@]};
-if [ "$arraySize" -gt 0 ]; then
-	echo "Press RETURN to retain current value. Or enter new value"
-fi
-IFS=';'
-#echo "Array size:${#values[@]}"
-for val in ${values[@]}
-        do
-                #echo -e "\nVal=$val"
-                if [ -z "`echo "$val" | tr -d '\n'`" ]; then
-                        continue
-                fi
-                lineNum=$(echo $val | awk -F: '{print $1}')
-                key=$(echo $val | awk -F: '{print $2}')
-                value=$(echo $val | awk -F: '{print $3}')
-                #trim value
-                value=$(echo $value| awk '{gsub(/^[ \t]+|[ \t]+$/,"")};1') #sed 's/^ *\(.*\) *$/\1/')
-                printf  "\n $key:[$value]?";
-                read user_value </dev/tty 2>/dev/tty
-                #read  -sn1 user_value < $(tty)
-                #stty echo
-                #-z "`echo "$VARIABLE" | tr -d '\n'`" `
-                if [ ! -z "`echo "$user_value" | tr -d '\n'`" ]; then
-                        printf "Changing :$value: to :$user_value:"
-                        sed -i -e ""$lineNum"s%"$value"%"$user_value"%" $connector_config
-                fi
-		#error
-		if [ $? != 0 ]; then
-        		echo "-- Sed returned an error when updating value "$key:$value". Please change this line manually in file $connector_config";
-		fi		
 done
-echo "--Configuration changed"
+if [ "$sshFwd_ans" == "N" ] || [ "$sshFwd_ans" == "n" ]; then
+	printf "\n--Configuration changed"
+        exit 1;
+fi
+
+params=( sshPortForward sshUser sshKey sshPort localAddress remotePort )
+values=( true 'dragon' '/home/dragon/.ssh/id_rsa' 22 '127.0.0.1' 2611 )
+read_file_parse
+prompt_user_entries
+# end new
+
+printf "\n--Configuration changed"
