-IONUserQuery, IONQueryCircuitStatistics, IONUserList, VerifyAdminSession, -DBUtil: Formatting added, checks for null SessionReply added, un-necessary TBD comments already implemented removed -ion.js, ion_admin.js: Added some checks to prevent some "undefined" or other Javascript errors which led to showing "server not reachable" -dojo-release-1.3.1-ion.tar.gz, IONUserModify, IONUserDelete: Files that I could not check in due to svn errors are added. web.xml updated to refer to these -INSTALL_GUIDE.docx, GETTINGSTARTED and QucikStart documens updated for ION -startServers.sh - replaced bask startIONUI which got deleted sometime between commit 9569 and now .sqls: Updated to ignore if duplicates (i.e sql scripts have already been run once) -Scripts: uncommented lines related to ION
git-svn-id: https://oscars.es.net/repos/oscars/trunk@9598 c75a6b91-02ef-0310-b74a-e20389c9c41d

diff --git a/tools/bin/idc-ionuiaccess b/tools/bin/idc-ionuiaccess
--- a/tools/bin/idc-ionuiaccess
+++ b/tools/bin/idc-ionuiaccess
@@ -24,14 +24,19 @@ fi
 #Subroutine to print usage details
 ###########################################################################
 printUsage() {
-	echo -e "\nusage idc-ionui <context> <option>"
+	echo -e "\nusage idc-ionuiaccess <context> <option>"
 	echo "<context> is one of: PRODUCTION|pro DEVELOPMENT|dev SDK|sdk"
 	echo "<option> is one of : ALLOW|allow DENY|deny"
 	exit 1
 }
 
 viewIONUIPort(){
-	Config=$(sh $OSCARS_DIST/bin/parseManifest.sh IONUIService $CONTEXT ionui jetty.xml)
+	#Config=$(sh $OSCARS_DIST/bin/parseManifest.sh IONUIService $CONTEXT ionui jetty.xml)
+	Config=$(sh $OSCARS_DIST/bin/parseManifest.sh IONUIService IONUIService $CONTEXT jetty.xml)
+	if [ -z $Config ]; then
+                echo "The configuration file is not found. Have you run the bin/copyTemplates.sh and/or bin/exportconfig commands?"
+                exit 1
+        fi
 	Service=$(echo $Config | awk -F/ '$1~//{print $2}')
 	Conf=$(echo $Config | awk -F/ '$1~//{print $3}')
 	Yaml=$(echo $Config | awk -F/ '$1~//{print $4}' | sed "s/'//g")
@@ -41,6 +46,12 @@ viewIONUIPort(){
 		configfile=$OSCARS_DIST/$Service/$Conf/$Yaml
 	fi
 	#echo "Config file:$configfile"
+	 if [ -z $configfile ] || [ ! -f $configfile ]; then
+                echo "The configuration file is not found. You either have to :"
+                echo "  1. Rerun this script after running copyTemplates.sh and/or bin/exportconfig, or "
+                echo "  2. Change files \"$OSCARS_HOME/WBUIService/conf/jetty.HTTP.xml or jetty.SSL.xml\" files manually to allow access to all hosts"
+                exit 1
+        fi
 
 	ALLOW="Allow"
 	DENY="Deny"
