Updates to shell scripts. Updated do_upgrade.sh for 0.4-0.5. Updated idc-* scripts to run from anywhere if OSCARS_HOME is set. Also updated idc-certadd to use keystore password as key password
git-svn-id: https://oscars.es.net/repos/oscars/trunk@7707 c75a6b91-02ef-0310-b74a-e20389c9c41d

diff --git a/tools/utils/idc-certadd b/tools/utils/idc-certadd
--- a/tools/utils/idc-certadd
+++ b/tools/utils/idc-certadd
@@ -11,12 +11,20 @@
 ###############################################################################
 # GLOBALS
 ###############################################################################
-if [ -z "$CATALINA_HOME" ]; then
-	echo "Required environment variable CATALINA_HOME is not set.";
-	exit 1;
+REPO_PATH=""
+if [ -n "$OSCARS_HOME" ]; then
+	REPO_PATH="$OSCARS_HOME/conf/axis-tomcat"
+elif [ -n "$CATALINA_HOME" ]; then
+	REPO_PATH="$CATALINA_HOME/shared/classes/repo"
+elif [ -d "./conf/axis-tomcat" ]; then
+	REPO_PATH="./conf/axis-tomcat"
+elif [ -d "./repo" ]; then
+	REPO_PATH="./repo"
+else
+    echo "ERROR: Unable to find keystore."
+    exit 1
 fi
-REPO_PATH="$CATALINA_HOME/shared/classes/repo";
-SERVER_PATH="$CATALINA_HOME/shared/classes/repo";
+SERVER_PATH="$REPO_PATH";
 
 ###############################################################################
 # SUBROUTINES
@@ -42,7 +50,7 @@ create_new_cert ()
     fi
     
     echo "-- Using keystore password from $REPO_PATH/rampConfig.xml";
-    keytool -genkey -alias $CERT_ALIAS -keystore $REPO_PATH/OSCARS.jks -storepass $KS_PASS -keyalg RSA -keypass password -validity $CERT_VALIDITY;
+    keytool -genkey -alias $CERT_ALIAS -keystore $REPO_PATH/OSCARS.jks -storepass $KS_PASS -keyalg RSA -keypass $KS_PASS -validity $CERT_VALIDITY;
     if [ $? != 0 ]; then
         echo "-- Keytool returned an error. See the error message above and please try again.";
         exit 1;
diff --git a/tools/utils/idc-certdel b/tools/utils/idc-certdel
--- a/tools/utils/idc-certdel
+++ b/tools/utils/idc-certdel
@@ -5,14 +5,22 @@
 # Deletes a certificate from a chosen keystore
 ###############################################################################
 
-if [ -z "$CATALINA_HOME" ]; then
-	echo "Required environment variable CATALINA_HOME is not set. Please run do_build.sh .";
-	exit 1;
+REPO_PATH=""
+if [ -n "$OSCARS_HOME" ]; then
+	REPO_PATH="$OSCARS_HOME/conf/axis-tomcat"
+elif [ -n "$CATALINA_HOME" ]; then
+	REPO_PATH="$CATALINA_HOME/shared/classes/repo"
+elif [ -d "./conf/axis-tomcat" ]; then
+	REPO_PATH="./conf/axis-tomcat"
+elif [ -d "./repo" ]; then
+	REPO_PATH="./repo"
+else
+    echo "ERROR: Unable to find keystore."
+    exit 1
 fi
 
 KS_PATH="";
 KS_PASS="";
-REPO_PATH="$CATALINA_HOME/shared/classes/repo";
 
 while [ 1 ]; do
     echo "Choose the keystore with the certificate you'd like to delete:";
@@ -26,7 +34,7 @@ while [ 1 ]; do
         KS_PATH="$REPO_PATH/OSCARS";
         break;
     elif [ "$OPCHOICE" == "2" ]; then
-        KS_PATH="$CATALINA_HOME/shared/classes/repo/ssl-keystore";
+        KS_PATH="$REPO_PATH/ssl-keystore";
         KS_PASS="oscars";
         break;
     else
diff --git a/tools/utils/idc-certsignreq b/tools/utils/idc-certsignreq
--- a/tools/utils/idc-certsignreq
+++ b/tools/utils/idc-certsignreq
@@ -6,11 +6,19 @@
 # OSCARS.jks.
 ###############################################################################
 
-if [ -z "$CATALINA_HOME" ]; then
-	echo "Required environment variable CATALINA_HOME is not set.";
-	exit 1;
+REPO_PATH=""
+if [ -n "$OSCARS_HOME" ]; then
+	REPO_PATH="$OSCARS_HOME/conf/axis-tomcat"
+elif [ -n "$CATALINA_HOME" ]; then
+	REPO_PATH="$CATALINA_HOME/shared/classes/repo"
+elif [ -d "./conf/axis-tomcat" ]; then
+	REPO_PATH="./conf/axis-tomcat"
+elif [ -d "./repo" ]; then
+	REPO_PATH="./repo"
+else
+    echo "ERROR: Unable to find keystore."
+    exit 1
 fi
-REPO_PATH="$CATALINA_HOME/shared/classes/repo";
 
 KS_PASS=`grep "org.apache.ws.security.crypto.merlin.keystore.password" $REPO_PATH/rampConfig.xml | sed -e 's/\s*<ramp:property name="org\.apache\.ws\.security\.crypto\.merlin\.keystore\.password">\(.*\)<\/ramp:property>/\1/'`;
 if [ $? != 0 ]; then
diff --git a/tools/utils/idc-kspasswd b/tools/utils/idc-kspasswd
--- a/tools/utils/idc-kspasswd
+++ b/tools/utils/idc-kspasswd
@@ -5,15 +5,22 @@
 # Changes the keystore passwords of sec-server.jks and sec-client.jks and stores
 # the changes in their associated .properties files.
 ###############################################################################
-
-if [ -z "$CATALINA_HOME" ]; then
-	echo "Required environment variable CATALINA_HOME is not set. Please run do_build.sh .";
-	exit 1;
+REPO_PATH=""
+if [ -n "$OSCARS_HOME" ]; then
+	REPO_PATH="$OSCARS_HOME/conf/axis-tomcat"
+elif [ -n "$CATALINA_HOME" ]; then
+	REPO_PATH="$CATALINA_HOME/shared/classes/repo"
+elif [ -d "./conf/axis-tomcat" ]; then
+	REPO_PATH="./conf/axis-tomcat"
+elif [ -d "./repo" ]; then
+	REPO_PATH="./repo"
+else
+    echo "ERROR: Unable to find keystore."
+    exit 1
 fi
 
-KS_PATH="$CATALINA_HOME/shared/classes/repo/OSCARS.jks";
-KS_CONF="$CATALINA_HOME/shared/classes/repo/axis2.xml";
-RAMP_CONF="$CATALINA_HOME/shared/classes/repo/rampConfig.xml";
+KS_PATH="$REPO_PATH/OSCARS.jks";
+RAMP_CONF="$REPO_PATH/rampConfig.xml";
 
 while [ 1 ]; do
     OLD_PASSWD="";
