A few small fixes for clean install process
git-svn-id: https://oscars.es.net/repos/oscars/trunk@7749 c75a6b91-02ef-0310-b74a-e20389c9c41d

diff --git a/tools/utils/idc-kspasswd b/tools/utils/idc-kspasswd
--- a/tools/utils/idc-kspasswd
+++ b/tools/utils/idc-kspasswd
@@ -58,10 +58,12 @@ while [ 1 ]; do
     
     #Change key password
     CERT_ALIAS=`grep "<ramp:user>.*</ramp:user>" $REPO_PATH/rampConfig.xml | sed -e 's/.*<ramp:user>\(.*\)<\/ramp:user>.*/\1/'`;
-    keytool -keypasswd -keystore $KS_PATH -keypass $OLD_PASSWD -new $NEW_PASSWD -storepass $NEW_PASSWD -alias $CERT_ALIAS
-    if [ $? != 0 ]; then 
-        echo "-- Keytool returned an error when changing your private key password. Please try again...";
-        exit 1;
+    if [ "$CERT_ALIAS" != "**keyEntry**" ]; then
+        keytool -keypasswd -keystore $KS_PATH -keypass $OLD_PASSWD -new $NEW_PASSWD -storepass $NEW_PASSWD -alias $CERT_ALIAS
+        if [ $? != 0 ]; then 
+            echo "-- Keytool returned an error when changing your private key password. Please try again...";
+            exit 1;
+        fi
     fi
     
     sed -i -e "s/<ramp:property name=\"org\.apache\.ws\.security\.crypto\.merlin\.keystore\.password\">.*<\/ramp:property>/<ramp:property name=\"org.apache.ws.security.crypto.merlin.keystore.password\">$NEW_PASSWD<\/ramp:property>/" $RAMP_CONF;
